apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    environment: production
    tier: frontend
    track: stable
  template:
    metadata:
      name: sevt-latest
      labels:
        environment: production
        tier: frontend
        track: stable
    spec:
      containers:
      - name: sevt-latest
        image: kamache/sevt:latest
        ports:
        - containerPort: 8080
